server:
  port: 8088
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  datasource:
    url: jdbc:postgresql://localhost:5432/ge-whale
    username: postgres
    password: nyl1024
    driver-class-name: org.postgresql.Driver

minio:
  endpoint: http://127.0.0.1
  port: 9000
  access-key: minio-root
  secret-key: minio-root
  bucket: minio-bucket
  secure: false