server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ge-whale
    username: postgres
    password: nyl1024
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  level:
    org.zszq: DEBUG
    org.springframework.security: DEBUG