server:
  port: 8082

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ge-whale
    username: postgres
    password: nyl1024
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

minio:
  endpoint: http://127.0.0.1
  port: 9000
  access-key: minio-root
  secret-key: minio-root
  secure: false
  bucket:
    music: music-bucket
    images: images-bucket

logging:
  level:
    org.zszq: DEBUG